# Introduction to Keras

In [ ]:
import numpy as np
from sklearn.datasets import load_iris

In [ ]:
iris = load_iris()
type(iris)

In [ ]:
print(iris.DESCR)

In [ ]:
X = iris.data 

In [ ]:
y = iris.target #labels

In [ ]:
#class 0 --> [1,0,0]
#class 1 --> [0,1,0]
#class 2 --> [0,0,1]

In [ ]:
# !pip install keras
# !pip install tensorflow
from tensorflow.keras.utils import to_categorical

In [ ]:
y = to_categorical(y)

In [ ]:
# y

In [ ]:
# split into train ant test set
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
print(f"Len all : {X.shape} | X_train : {X_train.shape} | X_test : {X_test.shape}")

In [ ]:
#standarize data
from sklearn.preprocessing import MinMaxScaler 

In [ ]:
np.array([5,10,15,20])/20

In [ ]:
scaler_object = MinMaxScaler()

In [ ]:
scaler_object.fit(X_train)

In [ ]:
scaled_X_train = scaler_object.transform(X_train)
scaled_X_test =  scaler_object.transform(X_test)
scaled_X_train[-3:]

In [ ]:
scaled_X_test[-3:] #all values are between 0-1

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
model = Sequential()
        #      8 neurons 4 features
model.add(Dense(8,input_dim=4,activation='relu'))#add layers
model.add(Dense(8,input_dim=4,activation='relu'))#add layers
model.add(Dense(3,activation='softmax'))#add layers[0.2,0.3,0.5]
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.summary()

In [ ]:
model.fit(scaled_X_train,y_train,epochs=150,verbose=2)

In [ ]:
predict_x=model.predict(scaled_X_test)
classes_x=np.argmax(predict_x,axis=1)

In [ ]:
classes_x

In [ ]:
y_test.argmax(axis=1)

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [ ]:
confusion_matrix(y_test.argmax(axis=1),classes_x)

In [ ]:
print(classification_report(y_test.argmax(axis=1),classes_x))

In [ ]:
accuracy_score(y_test.argmax(axis=1),classes_x)

In [ ]:
model.save('myfirstmodel.h5')#this save all the weigths of the model

In [ ]:
#to load the model
from tensorflow.keras.models import load_model

In [ ]:
new_model =load_model('myfirstmodel.h5')#be careful with name to no overwrtie

In [ ]:
predictions=new_model.predict(scaled_X_test)
classes = np.argmax(predictions,axis=1)

In [ ]:
classes

## Text Generation with LSTM (Keras)

In [1]:
def read_file(filepath):
    with open(filepath) as f:
        str_text=f.read()
    
    return str_text    

In [2]:
# read_file('moby_dick_four_chapters.txt')

In [3]:
#tokenize and clean
import spacy
nlp = spacy.load('en_core_web_lg',disable=['parser','tagger','ner'])

In [4]:
nlp.max_length = 1198623

In [5]:
def separate_punc(doc_text):
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']

In [6]:
d = read_file('moby_dick_four_chapters.txt')

In [7]:
tokens = separate_punc(d)

D:\VirtualEnvs\NLP_course\lib\site-packages\spacy\pipeline\lemmatizer.py:211: UserWarning: [W108] The rule-based lemmatizer did not find POS annotation for one or more tokens. Check that your pipeline includes components that assign token.pos, typically 'tagger'+'attribute_ruler' or 'morphologizer'.
  warnings.warn(Warnings.W108)


In [8]:
len(tokens)

11338

In [9]:
#create sequence of tokens
#25 words --> network predict #26

In [10]:
train_len = 25 + 1
text_sequences = []
for i in range(train_len,len(tokens)):
    seq = tokens[i-train_len:i]
    text_sequences.append(seq)

In [11]:
type(text_sequences)

list

In [12]:
' '.join(text_sequences[0])

'call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on'

In [13]:
' '.join(text_sequences[1])

'me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore'

In [14]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [15]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(text_sequences)

In [16]:
sequences = tokenizer.texts_to_sequences(text_sequences)

In [17]:
sequences[0]

[956,
 14,
 263,
 51,
 261,
 408,
 87,
 219,
 129,
 111,
 954,
 260,
 50,
 43,
 38,
 314,
 7,
 23,
 546,
 3,
 150,
 259,
 6,
 2713,
 14,
 24]

In [18]:
for i in sequences[0]:
    print(f"{i} : {tokenizer.index_word[i]}")
# tokenizer.index_word

956 : call
14 : me
263 : ishmael
51 : some
261 : years
408 : ago
87 : never
219 : mind
129 : how
111 : long
954 : precisely
260 : having
50 : little
43 : or
38 : no
314 : money
7 : in
23 : my
546 : purse
3 : and
150 : nothing
259 : particular
6 : to
2713 : interest
14 : me
24 : on


In [19]:
tokenizer.word_counts#gives a dict of the num of eache word appear

OrderedDict([('call', 27),
             ('me', 2471),
             ('ishmael', 133),
             ('some', 758),
             ('years', 135),
             ('ago', 84),
             ('never', 449),
             ('mind', 164),
             ('how', 321),
             ('long', 374),
             ('precisely', 37),
             ('having', 142),
             ('little', 767),
             ('or', 950),
             ('no', 1003),
             ('money', 120),
             ('in', 5647),
             ('my', 1786),
             ('purse', 71),
             ('and', 9646),
             ('nothing', 281),
             ('particular', 152),
             ('to', 6497),
             ('interest', 24),
             ('on', 1716),
             ('shore', 26),
             ('i', 7150),
             ('thought', 676),
             ('would', 702),
             ('sail', 104),
             ('about', 1014),
             ('a', 10377),
             ('see', 416),
             ('the', 15540),
             ('watery', 26),
  

In [20]:
vocabulary_size = len(tokenizer.word_counts)
vocabulary_size#unique words across the entire text

2718

In [21]:
type(sequences)

list

In [22]:
import numpy as np
sequences = np.array(sequences)
sequences

array([[ 956,   14,  263, ..., 2713,   14,   24],
       [  14,  263,   51, ...,   14,   24,  957],
       [ 263,   51,  261, ...,   24,  957,    5],
       ...,
       [ 952,   12,  166, ...,  262,   53,    2],
       [  12,  166, 2712, ...,   53,    2, 2718],
       [ 166, 2712,    3, ...,    2, 2718,   26]])

In [23]:
#split data into test & train

In [24]:
from keras.utils import to_categorical
sequences[:,:-1]#grab all except for the last columns, this column will be our label

array([[ 956,   14,  263, ...,    6, 2713,   14],
       [  14,  263,   51, ..., 2713,   14,   24],
       [ 263,   51,  261, ...,   14,   24,  957],
       ...,
       [ 952,   12,  166, ...,   11,  262,   53],
       [  12,  166, 2712, ...,  262,   53,    2],
       [ 166, 2712,    3, ...,   53,    2, 2718]])

In [25]:
sequences[:,-1]#here we have just the last value for each column, this will be our labels

array([  24,  957,    5, ...,    2, 2718,   26])

In [26]:
X=sequences[:,:-1]
y=sequences[:,-1]

In [27]:
y = to_categorical(y,num_classes=vocabulary_size+1)

In [28]:
seq_len = X.shape[1]

In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,LSTM,Embedding

In [30]:
#             50 NUMBER OF NEURONS, it recommend to be seq_len factor like seq_le*2 but this requires more time to train

def create_model(vocabulary_size, seq_len):
    model = Sequential()
    model.add(Embedding(vocabulary_size, 25, input_length=seq_len))
    model.add(LSTM(150, return_sequences=True))
    model.add(LSTM(150))
    model.add(Dense(150, activation='relu'))

    model.add(Dense(vocabulary_size, activation='softmax'))
    
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
   
    model.summary()
    
    return model

In [31]:
model=create_model(vocabulary_size+1,seq_len)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 25, 25)            67975     
                                                                 
 lstm (LSTM)                 (None, 25, 150)           105600    
                                                                 
 lstm_1 (LSTM)               (None, 150)               180600    
                                                                 
 dense (Dense)               (None, 150)               22650     
                                                                 
 dense_1 (Dense)             (None, 2719)              410569    
                                                                 
Total params: 787,394
Trainable params: 787,394
Non-trainable params: 0
_________________________________________________________________


In [32]:
from pickle import dump,load

In [33]:
model.fit(X,y,batch_size=128,epochs=200,verbose=1)

Epoch 1/200
89/89 [==============================] - 10s 82ms/step - loss: 6.8448 - accuracy: 0.0468
Epoch 2/200
89/89 [==============================] - 8s 86ms/step - loss: 6.3861 - accuracy: 0.0529
Epoch 3/200
89/89 [==============================] - 8s 87ms/step - loss: 6.3403 - accuracy: 0.0508
Epoch 4/200
89/89 [==============================] - 7s 83ms/step - loss: 6.2042 - accuracy: 0.0529
Epoch 5/200
89/89 [==============================] - 7s 81ms/step - loss: 6.1063 - accuracy: 0.0530
Epoch 6/200
89/89 [==============================] - 7s 80ms/step - loss: 5.9713 - accuracy: 0.0639
Epoch 7/200
89/89 [==============================] - 7s 79ms/step - loss: 5.8511 - accuracy: 0.0672
Epoch 8/200
89/89 [==============================] - 7s 79ms/step - loss: 5.7383 - accuracy: 0.0706
Epoch 9/200
89/89 [==============================] - 7s 80ms/step - loss: 5.6571 - accuracy: 0.0711
Epoch 10/200
89/89 [==============================] - 7s 78ms/step - loss: 5.5883 - accuracy: 0.072

89/89 [==============================] - 8s 88ms/step - loss: 2.9620 - accuracy: 0.3021
Epoch 82/200
89/89 [==============================] - 8s 94ms/step - loss: 2.8739 - accuracy: 0.3186
Epoch 83/200
89/89 [==============================] - 8s 91ms/step - loss: 2.7994 - accuracy: 0.3305
Epoch 84/200
89/89 [==============================] - 8s 94ms/step - loss: 2.7399 - accuracy: 0.3418
Epoch 85/200
89/89 [==============================] - 10s 108ms/step - loss: 2.6798 - accuracy: 0.3523
Epoch 86/200
89/89 [==============================] - 10s 111ms/step - loss: 2.6230 - accuracy: 0.3624
Epoch 87/200
89/89 [==============================] - 9s 102ms/step - loss: 2.5655 - accuracy: 0.3799
Epoch 88/200
89/89 [==============================] - 8s 93ms/step - loss: 2.4736 - accuracy: 0.3923
Epoch 89/200
89/89 [==============================] - 9s 100ms/step - loss: 2.4205 - accuracy: 0.4062
Epoch 90/200
89/89 [==============================] - 10s 109ms/step - loss: 2.3666 - accuracy: 0.

89/89 [==============================] - 8s 89ms/step - loss: 0.8255 - accuracy: 0.7994
Epoch 162/200
89/89 [==============================] - 8s 86ms/step - loss: 0.8107 - accuracy: 0.8052
Epoch 163/200
89/89 [==============================] - 8s 86ms/step - loss: 0.7778 - accuracy: 0.8136
Epoch 164/200
89/89 [==============================] - 8s 87ms/step - loss: 0.7570 - accuracy: 0.8176
Epoch 165/200
89/89 [==============================] - 8s 90ms/step - loss: 0.7599 - accuracy: 0.8205
Epoch 166/200
89/89 [==============================] - 8s 89ms/step - loss: 0.7285 - accuracy: 0.8283
Epoch 167/200
89/89 [==============================] - 8s 92ms/step - loss: 0.7118 - accuracy: 0.8354
Epoch 168/200
89/89 [==============================] - 8s 92ms/step - loss: 0.7226 - accuracy: 0.8282
Epoch 169/200
89/89 [==============================] - 10s 112ms/step - loss: 0.6915 - accuracy: 0.8397
Epoch 170/200
89/89 [==============================] - 9s 106ms/step - loss: 0.6655 - accuracy

In [34]:
model.save('my_mobydick_model.h5')

In [35]:
dump(tokenizer,open('my_simpletokenizer','wb'))

In [36]:
from tensorflow.keras.preprocessing.sequence import pad_sequences 

In [37]:
def generate_text(model, tokenizer, seq_len, seed_text, num_gen_words):
    '''
    INPUTS:
    model : model that was trained on text data
    tokenizer : tokenizer that was fit on text data
    seq_len : length of training sequence
    seed_text : raw string text to serve as the seed
    num_gen_words : number of words to be generated by model
    '''
    
    # Final Output
    output_text = []
    
    # Intial Seed Sequence
    input_text = seed_text
    
    # Create num_gen_words
    for i in range(num_gen_words):
        
        # Take the input text string and encode it to a sequence
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]
        
        # Pad sequences to our trained rate (50 words in the video)
        pad_encoded = pad_sequences([encoded_text], maxlen=seq_len, truncating='pre')
        
        # Predict Class Probabilities for each word
        pred_word_ind = model.predict(pad_encoded, verbose=0)
        pred_word_=np.argmax(pred_word_ind,axis=1)[0]
        
        # Grab word
        pred_word = tokenizer.index_word[pred_word_] 
        
        # Update the sequence of input text (shifting one over with the new word)
        input_text += ' ' + pred_word
        
        output_text.append(pred_word)
        
    # Make it look like a sentence.
    return ' '.join(output_text)

In [38]:
text_sequences[0]

['call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on']

In [39]:
import random 
random.seed(101)
random_pick= random.randint(0,len(text_sequences))

In [40]:
random_seed_text = text_sequences[random_pick]

In [41]:
seed_text = ' '.join(random_seed_text)
seed_text

"thought i to myself the man 's a human being just as i am he has just as much reason to fear me as i have"

In [42]:
generate_text(model,tokenizer,seq_len,seed_text=seed_text,num_gen_words=50)

"to be afraid of him better could do that comfortable that since all down into the idol yet took last far was n't coffin four low stooping or woollen as the case from a dark complexioned half ' ' not not rather a chief bagging a cape put it unmethodically"

In [43]:
#loading a model trained with 500 epochs
from tensorflow.keras.models import load_model


In [45]:
model = load_model('my_mobydick_model.h5')

In [ ]:
# tokenizer = load(open('epochBIG','rb'))

In [46]:
generate_text(model,tokenizer,seq_len,seed_text=seed_text,num_gen_words=25)

"to be afraid of him better could do that comfortable that since all down into the idol yet took last far was n't coffin four"