<h1>TOP MODELING</h1>

In [1]:
import pandas as pd

In [ ]:
npr = pd.read_csv('npr.csv')
npr.head()#this time we don't have labels

In [7]:
# npr['Article'][4000]
len(npr)

11992

In [9]:
#Preprocesing
from sklearn.feature_extraction.text import CountVectorizer

**`max_df`**` : float in range [0.0, 1.0] or int, default=1.0`<br>
When building the vocabulary ignore terms that have a document frequency strictly higher than the given threshold (corpus-specific stop words). If float, the parameter represents a proportion of documents, integer absolute counts. This parameter is ignored if vocabulary is not None.

**`min_df`**` : float in range [0.0, 1.0] or int, default=1`<br>
When building the vocabulary ignore terms that have a document frequency strictly lower than the given threshold. This value is also called cut-off in the literature. If float, the parameter represents a proportion of documents, integer absolute counts. This parameter is ignored if vocabulary is not None.

In [10]:
cv = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')

In [11]:
dtm = cv.fit_transform(npr['Article'])

In [14]:
dtm.shape

(11992, 54777)

## LDA

In [15]:
from sklearn.decomposition import LatentDirichletAllocation

In [16]:
LDA = LatentDirichletAllocation(n_components=7,random_state=42)

In [17]:
# This can take awhile, we're dealing with a large amount of documents!
LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

## Showing Stored Words

In [30]:
#Grab the vocabulary
len(cv.get_feature_names_out())
cv.get_feature_names_out()[5000]

'bask'

In [32]:
#Grab the topics
import random
random_word_id = random.randint(0,54777)
cv.get_feature_names_out()[random_word_id]

'helmed'

In [38]:
single_topic=LDA.components_[0]

In [39]:
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993], dtype=int64)

In [40]:
single_topic.argsort()[-10:]

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993], dtype=int64)

In [44]:
top_twenty_words = single_topic.argsort()[-20:]

In [45]:
for index in top_twenty_words:
    print(cv.get_feature_names_out()[index])

president
state
tax
insurance
trump
companies
money
year
federal
000
new
percent
government
company
million
care
people
health
said
says


In [18]:
#Grab the highest probability words per topic

In [47]:
for i,topic in enumerate(LDA.components_):
    print(f"THE TOP 15 WORDS FOR TOPIC{i}")
    print([cv.get_feature_names_out()[index] for index in topic.argsort()[-15:]])
    print('\n')
    print('\n')

THE TOP 15 WORDS FOR TOPIC0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']




THE TOP 15 WORDS FOR TOPIC1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']




THE TOP 15 WORDS FOR TOPIC2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']




THE TOP 15 WORDS FOR TOPIC3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']




THE TOP 15 WORDS FOR TOPIC4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']




THE TOP 15 WORDS FOR TOPIC5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know', 'think', '

### Attaching Discovered Topic Labels to Original Articles

In [51]:
dtm.shape

(11992, 54777)

In [56]:
topic_results=LDA.transform(dtm)

In [57]:
topic_results[0]#see the probability of a document belong to a particular topic

array([1.61040465e-02, 6.83341493e-01, 2.25376318e-04, 2.25369288e-04,
       2.99652737e-01, 2.25479379e-04, 2.25497980e-04])

In [59]:
topic_results[0].argmax()

1

In [60]:
npr['Topic'] = topic_results.argmax(axis=1)

In [61]:
npr

Article  Topic
0      In the Washington of 2016, even when the polic...      1
1        Donald Trump has used Twitter  —   his prefe...      1
2        Donald Trump is unabashedly praising Russian...      1
3      Updated at 2:50 p. m. ET, Russian President Vl...      1
4      From photography, illustration and video, to d...      2
...                                                  ...    ...
11987  The number of law enforcement officers shot an...      1
11988    Trump is busy these days with victory tours,...      4
11989  It’s always interesting for the Goats and Soda...      3
11990  The election of Donald Trump was a surprise to...      4
11991  Voters in the English city of Sunderland did s...      0

[11992 rows x 2 columns]

## Non-Negative Matrix

In [62]:
import pandas
npr= pd.read_csv('npr.csv')
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [64]:
# Preprocess
from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.feature_extraction.text import TfidfVectorizer

In [66]:
tfidf = TfidfVectorizer(max_df=0.95,min_df=2,stop_words='english')

In [67]:
dtm= tfidf.fit_transform(npr['Article'])

In [68]:
dtm.shape

(11992, 54777)

In [69]:
from sklearn.decomposition import NMF

In [71]:
nmf_model = NMF(n_components=7,random_state=42)

In [72]:
nmf_model.fit(dtm)

NMF(n_components=7, random_state=42)

In [73]:
tfidf.get_feature_names_out()[2300]

'albala'

In [77]:
for i,topic in enumerate(nmf_model.components_):
    print(f"THE TOP 15 WORDS FOR TOPIC # {i}")
    print([tfidf.get_feature_names_out()[index] for index in topic.argsort()[-15:]])
    print('\n')

THE TOP 15 WORDS FOR TOPIC # 0
['new', 'research', 'like', 'patients', 'health', 'disease', 'percent', 'women', 'virus', 'study', 'water', 'food', 'people', 'zika', 'says']


THE TOP 15 WORDS FOR TOPIC # 1
['gop', 'pence', 'presidential', 'russia', 'administration', 'election', 'republican', 'obama', 'white', 'house', 'donald', 'campaign', 'said', 'president', 'trump']


THE TOP 15 WORDS FOR TOPIC # 2
['senate', 'house', 'people', 'act', 'law', 'tax', 'plan', 'republicans', 'affordable', 'obamacare', 'coverage', 'medicaid', 'insurance', 'care', 'health']


THE TOP 15 WORDS FOR TOPIC # 3
['officers', 'syria', 'security', 'department', 'law', 'isis', 'russia', 'government', 'state', 'attack', 'president', 'reports', 'court', 'said', 'police']


THE TOP 15 WORDS FOR TOPIC # 4
['primary', 'cruz', 'election', 'democrats', 'percent', 'party', 'delegates', 'vote', 'state', 'democratic', 'hillary', 'campaign', 'voters', 'sanders', 'clinton']


THE TOP 15 WORDS FOR TOPIC # 5
['love', 've', 'don

In [78]:
topic_resuslt = nmf_model.transform(dtm)

In [80]:
topic_results[0].argmax()

1

In [81]:
npr['Topic'] = topic_results.argmax(axis=1)
np.head()

In [83]:
mytopic_dict = {1:'Politics',2:'Legis',3:'National Sec',4:'Votes',5:'LifeStyle',6:'Education'}
npr['Topic Label'] = npr['Topic'].map(mytopic_dict)
npr.head()

Article  Topic Topic Label
0  In the Washington of 2016, even when the polic...      1    Politics
1    Donald Trump has used Twitter  —   his prefe...      1    Politics
2    Donald Trump is unabashedly praising Russian...      1    Politics
3  Updated at 2:50 p. m. ET, Russian President Vl...      1    Politics
4  From photography, illustration and video, to d...      2       Legis